config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations], controllers: {
    #これらを書かないとログイン時に呼び出されるアクションがuserのroutingと一致してしまう。
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
  }

  authenticated :user do
    devise_scope :admin do
      get 'admins/sign_up' => 'devise/registrations#new', as: :new_admin_registration
      post 'admins/sign_up' => 'devise/registrations#create', as: :admin_registration
    end
  end

  devise_for :users, skip: [:registrations], controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
  }

  resources :users
  root"posts#index"
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaiyanSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <% if user_signed_in? %>
    <% if current_user.admin? %>
      <%= link_to "患者新規登録", new_admin_registration_path %>
      <h3>ログイン中の病院管理者！userのメアド</h3>
      <%= current_user.email %> 
      <%= button_to '病院管理者ログアウト', destroy_user_session_path, method: :delete %>  
    <% else %>
      <p>病院userのメアド</p>
      <%= current_user.email %>
      <%= button_to 'userログアウト', destroy_user_session_path, method: :delete %>
    <% end %>
  <% else %>
        <%= link_to "病院userログイン", new_user_session_path %>
  <% end %>

  <% if admin_signed_in? %>
    <h3>ログイン中の患者adminのメアド</h3>
    <%= current_admin.email %>
    <%= button_to '患者ログアウト', destroy_admin_session_path, method: :delete %>
  <% else %>
    <h3>患者はログアウト中</h3>
    <%= link_to "患者Log in", new_admin_session_path %><br>
  <% end %>

    <%= yield %>
  </body>
</html>